title: Mark Kamuda
description: Personal Blog for Mark

url: https://github.com/kamuda1
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Contact
   url: /contact

social:
   github: kamuda1
   email: kamuda1@illinois.com

google_analytics: "UA-58263416-1"
